### ISSUE TITLE
Clarification needed for PM2.3

### ISSUE THREAD

**Issue by daniilkarpov** [NAG-DevOps/splints#18]
Hello @smokhov, it is unclear to us what kind of implementation needs to be created for "(c) Teams 3 and 8: Refactor rt/splints a-la fp/v11/splints. The main class would be RT with the API createIssue() and editIssue() from ISplints. There ought to be Config and Constants." From my understanding we need to create a REST post() method for this but RT already has a REST service: https://rt-wiki.bestpractical.com/wiki/REST#Ticket_Create. So do we call this REST service and our REST service acts as a wrapper of sorts? Thank you

**Comment by smokhov** [comment]
@daniilkarpov -- you are mixing two things -- refactoring and REST implementation.

(1) refactoring here simply means:

- create a class `RT` in the likeness of `FootPrints11`
- make it so that it implements `ISplints` for your part
- refactor `RtCreateIssue.java` into `RT.createIssue()` (for the appropriate team)
- do the same for `RTEditTicket.java` to be `RT.editIssue()`
- the class has to use `Constants` and `Config` classes for now defined separately for the RT under the `rt` package

Just like it was done for `FootPrints11` and `CreateIssue` and `EditIssue` classes.

(2) REST stuff is separate from this refactoring issue

The answer here is yes, your REST is a kind of wrapper for another REST or SOAP, so it's more closer to a a mashup

**Comment by vincent-fugnitto** [comment]
@smokhov for the test REST client (part j), could we create a simple standalone angular app which simply consumes our REST API and provides some visual representation of our JSON data or did you have other ideas in mind?

**Comment by smokhov** [comment]
(belatedly) @vincent-fugnitto -- I did not specifically ask for Angular here (we use Angular in MARFCAT), more like barebone client similar to PM2.1, but it is possible to have used Angular in PM2.3.

**Comment by smokhov** [comment]
Covered in 452d7cf; follow up fixes will be done later.
